### ISSUE TITLE
Use species instead of cities data set for explaining joins

### ISSUE THREAD

**Issue by RoelBrouwer** [UtrechtUniversity/workshop-introduction-to-python#45]
In the third part of the afternoon session, specifically the section on joining DataFrames, we now use a (smaller) dataset on EU capitals (`EU_capitals_tiny.csv`) & Dutch cities (`Netherlands_town_weather_tiny.csv`). These datasets are not used anywhere else.

The argument in favor of using these datasets, is that they are small, easy to understand DataFrames to get the concepts across. The argument against their use, is that it is inconsistent with the rest of the course, where we use the `species` and `surveys` datasets for everything.

We can do the same with small subsets of the `species` and `surveys` DataFrames that we work with for the rest of the afternoon session, but it requires a little more 'work' in getting useful examples.

We decided to keep the city-data for now, and evaluate whether to change this after the pilot.

**Comment by nehamoopen** [comment]
Can this issue be closed @RoelBrouwer? Just doing a review.

**Comment by RoelBrouwer** [comment]
Technically, not yet, no. We discussed this afternoon that we will indeed remove the capital/town datasets and use the species and surveys datasets in chapter 8. So the decision has been made, but it still has to be done. I will (in time) link it to my eventual pull-request so that it will close once that is merged. It is on my radar.
