### ISSUE TITLE
Skip or only referencing 'Dataset cleaning'

### ISSUE THREAD

**Issue by chStaiger** [UtrechtUniversity/workshop-introduction-to-python#62]
Afternoon session part2 is too long. We suggest to skip and only reference the dataset cleaning part.

**Comment by nehamoopen** [comment]
Hmm I don't know, I think dataset cleaning is pretty relevant... I wonder if we can reduce demos/exercises in different parts? Let's discuss it further at the end of the pilot.

**Comment by DorienHuijser** [comment]
I don't know, the whole pandas thing seems very useful indeed. Only suggestion would be to cut the "Grouping, Indexing, Slicing, and Subsetting DataFrames" part up into multiple parts because it seems really long.
