### ISSUE TITLE
Check if anaconda navigator is available via software center

### ISSUE THREAD

**Issue by jelletreep** [UtrechtUniversity/workshop-introduction-to-python#65]
Is it possible to install anaconda navigator on UU managed windows laptops? If not we should try to get it in the software center (this is a simple request we did for e.g. git bash and github desktop earlier)

**Comment by DorienHuijser** [comment]
It's not in my software center! Worth asking indeed!

**Comment by nehamoopen** [comment]
it's not available, i asked them to put it in and they said they don't do it unless more than 5 people request it - but once the course starts, they will get reach that number...so we should put in another request

this is linked to issue #55

**Comment by DorienHuijser** [comment]
I also put in a request today. Hopefully they will put it in the software center before the first workshop starts! Do we have a cloud-based solution as an alternative?

**Comment by jelletreep** [comment]
Request Approved!

**Comment by jelletreep** [comment]
However it is declined by Application administration, because apparently from what I understood it is badly designed with too many updates in the Program files folder. Therefore they suggest to request installation rights via the self service portal. I am not sure how this works and if this is easy/fast, @nehamoopen @DorienHuijser could you try this route? I am also looking at alternatives, e.g. Visual Studio Code? Is that maybe already available? I will check with the Digital Humanities that organizes a Python workshop as well

**Comment by nehamoopen** [comment]
For now, I think instructing participants to request Anaconda Navigator on an individual basis might be alright. It's worth noting that not all researchers have UU-managed laptops and we are addressing a subset of participants. It's a minor hassle but it will be good for them to just get Anaconda installed properly via the right channels and then it's done with.

Could an alternative be for the Software Center to provide vanilla installations of Python and/or Jupyter? I think you can install everything with pip as well. Dunno how they could make that available...

Visual Studio Code is not available via the Software Center, I had to download that.

Good to check with the DH Team about their instructions for UU-managed laptops!

**Comment by jelletreep** [comment]
> For now, I think instructing participants to request Anaconda Navigator on an individual basis might be alright. It's worth noting that not all researchers have UU-managed laptops and we are addressing a subset of participants. It's a minor hassle but it will be good for them to just get Anaconda installed properly via the right channels and then it's done with.

Agree! If it works fine this may be the best option, would be good if someone with a managed laptop can test it and if necessary write a few lines about the steps?

> Could an alternative be for the Software Center to provide vanilla installations of Python and/or Jupyter? I think you can install everything with pip as well. Dunno how they could make that available...

I looked into this a tiny bit, it may be possible via pip, but it looks like you will end up with something that needs to be started via command prompt.

If VS Code does not have the same problems as Anaconda this might be an alternative
