### ISSUE TITLE
Revisit Visualization exercises

### ISSUE THREAD

**Issue by jelletreep** [UtrechtUniversity/workshop-introduction-to-python#78]
@StefanoRapisarda, I am assigning this to you since it is connected to your task to revisit the visualization chapter

- [x] Exercise 12
I wanted to add answers for exercise 12, but I was really struggling to create 3 different plots using the pandas plot method. Creating new plots with different columns doesn't make sense for the scatter type plot, since the other columns are categorical variables. It would be nice to e.g. create a boxplot with 2 boxes for different sexes, but one would have to go to the .plot.box  method (kind='box' does not provide satisfactory results), this is confusing and not flexible enough in my opinion. Since we are revisiting the visualization chapter anyway, perhaps we could change this. I think it is also confusing to introduce both the plotting methods from pandas and matplotlib. Perhaps choose either matplotlib or seaborn and stick with that.
- [x] Exercise 13
Here an answer should be added. We can do it when we settle on exercise 12 and 13.

**Comment by StefanoRapisarda** [comment]
I guess you meant exercise 13 and 14.

Exercise 13 is now a multiplot of the same data with different filtering criteria. At this point they should have enough knowledge from the book material to make the exercise with minimal "external" (pandas and matplotlib documentation) consultation. About plt.scatter() and PandasDataFrame plot(), I still kept both of them in the book material, but I improved the study cases and made more clear what they have in common, what are their differences, and when to use one or the other. I still think it is a good idea to address both as it may be confusing deciding when to use pandas methods (as done in previous chapters in the book) and when to use matplotlib functions;

I deleted exercise 14, it is now included in 13. I think the lecture can be, as a matter of fact, concluded with exercise 13, and very briefly mentioning the extra paragraphs in the book. In this way, if there is extra time, the helper if free to decide if also showing the next paragraphs in more details (plotting grouped data and saving plots).
